# WhatATheme
markdown: kramdown

# URL of the Site
url: 'https://naturalcap.cn'
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: 自然数资本
# Description of the Site
description: 专注于为前沿科技初创企业提供融资顾问服务，让科技创业更简单!
# URL of Image of the Site
logo: assets\images\logo_for_web.png
logoheight: 40
# Keywords of the Site
site-keywords: 自然数资本，naturalcap，natural capital
# URL for the Image of custom Favicon
favicon-url: /assets/images/Nforweb.ico
# URL for the Image of about image
about-image: assets\images\AI-gen-airspace-v1.jpg
# URL for the Image of team image
team-image: assets\images\AI-gen-astronaut-v1.jpg
# URL for the Image of contact image
contact-image: assets\images\qrcode_for_gzh.jpg

# Google Analytics
#  google-analytics: UA-163806439-1


# About Us
logo-about-1: 自然数资本，专注于为前沿科技初创企业提供融资顾问服务。
logo-about-2: 当人类用数字描述自然时，科学便迈进了新的纪元。而每一个人认识数字的起点，是自然数，即从0到+∞的整数。在我们看来，自然数象征着真实之美、简洁之美、自由之美，也象征着创业从0到N的伟大历程。
company-about: 自然数资本，依托科研和创投复合背景团队，坚持标准化和数字化理念，敏锐捕捉技术突破，系统梳理商业价值，高效对接创业融资，让科技创业更简单！
team-about-1: 我们毕业于清华大学、复旦大学等，主修控制工程、电气工程、飞行器设计等专业，取得工学或MBA硕士学位。曾参与国家自然科学基金项目，发表SCI论文、EI论文、专利数10+，获得清华大学优秀论文奖；曾在阿里巴巴、联想、Discover Financial Services、平安等从事算法研发工作。
team-about-2: 我们曾在蚂蚁集团投资部、字节跳动投资部、达晨财智、线性资本等从事风险投资工作，撰写行业研究报告10+，主导或参与投资案例数十个，涉及基础软件、数据智能、信息安全、工业科技、智能硬件等。
team-about-3: 我们持续加深与风险投资机构的联系，可触达投资机构600+，投资人1400+。
# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
