# WhatATheme
markdown: kramdown

# URL of the Site
url: 'http://Jovieeo.github.io'
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: 自然数资本
# Description of the Site
description: 让科技创业更简单!
# URL of Image of the Site
logo: assets\images\logo.png
logoheight: 8
# Keywords of the Site
site-keywords: 科技, 创业
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940


# Google Analytics
#  google-analytics: UA-163806439-1


# About Us
company-about: 自然数资本专注于高新技术初创企业的融资服务，依托科研和创投复合背景团队，坚持标准化和数字化的理念，敏锐捕捉技术突破，系统梳理商业价值，高效助力创业融资，让科技创业更简单！
team-about: 团队成员毕业于清华大学、复旦大学、哈尔滨工业大学等，均取得工学及MBA硕士学位，发表数篇SCI和EI论文，曾工作于Discover Financial Services、联合电子、字节跳动投资部、线性资本、火山石资本等，从事技术或投资的平均年限超过5年

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
