# WhatATheme
markdown: kramdown

# URL of the Site
url: 'http://www.naturalcap.cn'
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: 自然数资本
# Description of the Site
description: 让科技创业更简单!
# URL of Image of the Site
logo: assets\images\logo_for_web.png
logoheight: 40
# Keywords of the Site
site-keywords: 科技, 创业
# URL for the Image of custom Favicon
favicon-url: /assets/images/n_for_web.png
# URL for the Image of about image
about-image: assets\images\AI-gen-airspace-v1.jpg
# URL for the Image of team image
team-image: assets\images\AI-gen-astronaut-v1.jpg
# URL for the Image of contact image
team-image: assets\images\qrcode_for_gzh.jpg

# Google Analytics
#  google-analytics: UA-163806439-1


# About Us
logo-about-1: 当人类用数字描述自然时，科学便向前迈进了一大步。而每一个人出生学会的第一串数字就是自然数，零到无穷的非负整数。
logo-about-2: 在我们心里，自然数，代表着创业追寻有序增长的伟大历程，也代表着人类求是、理性、严谨、创新的科学精神！
company-about: 自然数资本，专注于为前沿科技初创企业提供融资服务。依托科研和创投复合背景团队，坚持标准化和数字化理念，敏锐捕捉技术突破，系统梳理商业价值，高效助力创业融资，让科技创业更简单！
team-about: 核心团队毕业于清华大学、复旦大学、哈尔滨工业大学等，取得工学硕士及MBA硕士学位，发表SCI和EI论文数篇，曾工作于Discover Financial Services、联合电子、字节跳动投资部、线性资本、火山石资本等，从事技术或投资的平均年限超过5年！

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
